config/routes.rb
Rails.application.routes.draw do


  resources :add_time_to_appointments

  resources :sessions
  resources :meetings
  resources :appointments

  resources :user
  root 'sessions#new'
  # get '/login' => 'home#login'
  # post '/login' => 'appointments#index'
  # get '/logout' => 'home#destroy'
    get '/index' => 'appointments#index'
    # get    '/help'   => 'https://walterbondcoaching.com'
    get    '/signup' => 'appointments#new'
    get    '/login' => 'sessions#new'
    post   '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    get '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# GET '/abc' do
#   /app/views/meetings/_form
# end

app/models/add_time_to_appointment.rb
class AddTimeToAppointment < ApplicationRecord
end

app/controllers/add_time_to_appointments_controller.rb
class AddTimeToAppointmentsController < ApplicationController
  before_action :set_add_time_to_appointment, only: [:show, :edit, :update, :destroy]

  # GET /add_time_to_appointments
  # GET /add_time_to_appointments.json
  def index
    @add_time_to_appointments = AddTimeToAppointment.all
  end

  # GET /add_time_to_appointments/1
  # GET /add_time_to_appointments/1.json
  def show
  end

  # GET /add_time_to_appointments/new
  def new
    @add_time_to_appointment = AddTimeToAppointment.new
  end

  # GET /add_time_to_appointments/1/edit
  def edit
  end

  # POST /add_time_to_appointments
  # POST /add_time_to_appointments.json
  def create
    @add_time_to_appointment = AddTimeToAppointment.new(add_time_to_appointment_params)

    respond_to do |format|
      if @add_time_to_appointment.save
        format.html { redirect_to @add_time_to_appointment, notice: 'Add time to appointment was successfully created.' }
        format.json { render :show, status: :created, location: @add_time_to_appointment }
      else
        format.html { render :new }
        format.json { render json: @add_time_to_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_time_to_appointments/1
  # PATCH/PUT /add_time_to_appointments/1.json
  def update
    respond_to do |format|
      if @add_time_to_appointment.update(add_time_to_appointment_params)
        format.html { redirect_to @add_time_to_appointment, notice: 'Add time to appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @add_time_to_appointment }
      else
        format.html { render :edit }
        format.json { render json: @add_time_to_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_time_to_appointments/1
  # DELETE /add_time_to_appointments/1.json
  def destroy
    @add_time_to_appointment.destroy
    respond_to do |format|
      format.html { redirect_to add_time_to_appointments_url, notice: 'Add time to appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_time_to_appointment
      @add_time_to_appointment = AddTimeToAppointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def add_time_to_appointment_params
      params.require(:add_time_to_appointment).permit(:time)
    end
end

app/helpers/add_time_to_appointments_helper.rb
module AddTimeToAppointmentsHelper
end

app/views/add_time_to_appointments/_form.html.erb
<%= form_with(model: add_time_to_appointment, local: true) do |form| %>
  <% if add_time_to_appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(add_time_to_appointment.errors.count, "error") %> prohibited this add_time_to_appointment from being saved:</h2>

      <ul>
      <% add_time_to_appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time, id: :add_time_to_appointment_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/add_time_to_appointments/edit.html.erb
<h1>Editing Add Time To Appointment</h1>

<%= render 'form', add_time_to_appointment: @add_time_to_appointment %>

<%= link_to 'Show', @add_time_to_appointment %> |
<%= link_to 'Back', add_time_to_appointments_path %>

app/views/add_time_to_appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Add Time To Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @add_time_to_appointments.each do |add_time_to_appointment| %>
      <tr>
        <td><%= add_time_to_appointment.time %></td>
        <td><%= link_to 'Show', add_time_to_appointment %></td>
        <td><%= link_to 'Edit', edit_add_time_to_appointment_path(add_time_to_appointment) %></td>
        <td><%= link_to 'Destroy', add_time_to_appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Add Time To Appointment', new_add_time_to_appointment_path %>

app/views/add_time_to_appointments/new.html.erb
<h1>New Add Time To Appointment</h1>

<%= render 'form', add_time_to_appointment: @add_time_to_appointment %>

<%= link_to 'Back', add_time_to_appointments_path %>

app/views/add_time_to_appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @add_time_to_appointment.time %>
</p>

<%= link_to 'Edit', edit_add_time_to_appointment_path(@add_time_to_appointment) %> |
<%= link_to 'Back', add_time_to_appointments_path %>