config/routes.rb
Rails.application.routes.draw do


  resources :add_time_to_appointments

  resources :sessions
  resources :meetings
  resources :appointments

  resources :user
  root 'sessions#new'
  # get '/login' => 'home#login'
  # post '/login' => 'appointments#index'
  # get '/logout' => 'home#destroy'
    get '/index' => 'appointments#index'
    # get    '/help'   => 'https://walterbondcoaching.com'
    get    '/signup' => 'appointments#new'
    get    '/login' => 'sessions#new'
    post   '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    get '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# GET '/abc' do
#   /app/views/meetings/_form
# end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @user = current_user
    @appointments = current_user.appointments
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = current_user.appointments.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = current_user.appointments.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:name, :date, :hour, :minutes, :amorpm, :goal)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :appointment_Name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :appointment_Date %>
  </div>

  <div class="field">
    <%= form.label :hour %>
    <%= form.text_field :hour, id: :appointment_Hour %>
  </div>
  <div class="field">
    <%= form.label :minute %>
    <%= form.text_field :minutes, id: :appointment_Minutes %>
  </div>
  <div class="field">
    <%= form.label :amorpm %>
    <%= form.text_field :amorpm, id: :appointment_Amorpm %>
  </div>
  <div class="field">
    <%= form.label :goal %>
    <%= form.text_area :goal, id: :appointment_Goal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Appointment Scheduler</h1>
  <p>Walter is available the entire month of July</p>
</div>


<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Hour</th>
      <th>   Minutes   </th>
      <th>   Am or PM   </th>
      <th>   Goal    </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.name %></td>
        <td><%= appointment.date %></td>
        <td><%= appointment.hour %></td>
        <td><%= appointment.minutes %></td>
        <td><%= appointment.amorpm %></td>
        <td><%= appointment.goal %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @appointment.hour %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @appointment.minutes %>
</p>

<p>
  <strong>Am or PM:</strong>
  <%= @appointment.amorpm %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @appointment.goal %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>